### ISSUE TITLE
Incompatable with Adafruit Huzzah32 (ESP32) in Arduino IDE

### ISSUE THREAD

**Issue by JoelEB** [hideakitai/MAX17048#1]
Thanks for the great library! I have a MAX17048 on a board I designed recently. The board runs via an Adafruit Huzzah32 (ESP32). I built a prototype with the MAX17043, which worked great. I switched to the newer 17048 without testing the two together first, though I had tested the 17048  independently on a different board (Qduino mini) with this library with success. I am able to connect an Arduino Pro Mini 3.3V to the SDA, SCL and GND lines on my board and communicate with the MAX17048, so I know the circuitry is functional. But when I attach the Huzzah32, it returns zeros for all readings. I am using your library and the included example. I have pull-ups on both lines and have confirmed the hardware works with other boards. I looked at the MAX17043 library to see what differences there could be to explain why it works on the Huzzah32 but this library does not. I tried adding 'Arduino.h' and a few other small differences, but nothing seemed to do the trick. Any time you have to put towards this is greatly appreciated. Thanks.

**Comment by hideakitai** [comment]
I'm sorry for the late reply, thank you for the feedback.
So, you have tested the MAX17048 with this library, and ESP32 with MAX17043?
And ESP32+MAX17048 with this library didn't work?
I have used this library with ESP32 in the previous project, so library itself works well.

One of the possible reason why I2C returns zero is esp32-arduino's I2C unstability. Please check this replacement of I2C (Wire) library.
https://desire.giesecke.tk/index.php/2018/04/20/how-to-use-stickbreakers-i2c-improved-code/

ESP32 + this library works well, so I will close this issue.
But let me know more info (codes, schematic, etc.)  if you still have the problem with them.
Thank you for your feedback!
