### ISSUE TITLE
Attiny 85 compatibility

### ISSUE THREAD

**Issue by geologic** [hideakitai/MAX17048#2]
Hi

I tried your code with attiny85, but it does not compile:

(...) \libraries\Wire\src\utility\twi.c:76:16: error: 'SDA' undeclared (first use in this function)

   digitalWrite(SDA, 1);

 i'm using your example file, without the Serial() stuff
Any idea why?

**Comment by geologic** [comment]
Well, after searching the web it seems I2C hardware from attiny85 is different from Uno (atmega328p), the workaround is to use a compatible I2C library like TinyWireM instead of Wire.

At line 48 of Max17048.h i changed: 

`#include <Wire.h> to #include <TinyWireM.h>`

I made a simple example:

```
#include "TinyWireM.h"
#include "MAX17048.h"                            
MAX17048 pwr_mgmt;

void setup() {

TinyWireM.begin();
pwr_mgmt.attatch(TinyWireM);
}
```

But i'm still having compiler errors:

(...) libraries\MAX17048/MAX17048.h:47:22: error: 'TwoWire' has not been declared

         void attatch(TwoWire& w) { wire = &w; }


Any idea?

**Comment by hideakitai** [comment]
Hi, I think it is because the name of type `TinyWireM` is not `TwoWire`. Please change `TwoWire` to `TinyTwi`? Or you can use [this `TinyWireM`](https://github.com/adafruit/Adafruit_Arduino_Boards/tree/master/libraries/Wire). Maybe it is compilable,

**Comment by geologic** [comment]
I finally manage to compile the code, i had to change TwoWire to USI_TWI.

Now i have to solve another problem, TinyWireM library is too big for my 8k of memory, but that's another story...

Thanks for your help.
