### ISSUE TITLE
Max17049

### ISSUE THREAD

**Issue by geologic** [hideakitai/MAX17048#3]
Hi

Does your code works with MAX17049 2 cell fuel gauge? How your library distinguish between 1 cell MAX17048 vs 2 cell MAX17049?
I tried your example but i'm always getting:
```

VCELL ADC : 65535
VCELL V   : 5.12
VCELL SOC : 255 %
VCELL SOC : 256.00 %
```

Thanks

**Comment by hideakitai** [comment]
Please declare
 
```C++
MAX17049 pwr_mgmt;
```

instead of 

```C++
MAX17048 pwr_mgmt;
```

**Comment by hideakitai** [comment]
Close this issue but if you still have the problem, please feel free to reopen the issue.
