### ISSUE TITLE
excuse me!

### ISSUE THREAD

**Issue by GaoShouA** [hideakitai/MAX17048#4]
What is the iic pin used by max17048 on the esp8266 general board?

**Comment by hideakitai** [comment]
@zhizaibangshou SDA 4 and SCL 5 is the default but you can change them. Please google "ESP8266 i2c pins".

**Comment by GaoShouA** [comment]
谢谢，What is the peripheral circuit of max17048?

**Comment by hideakitai** [comment]
Please see the datasheet https://datasheets.maximintegrated.com/en/ds/MAX17048-MAX17049.pdf
