### ISSUE TITLE
Wrong output with max 17048

### ISSUE THREAD

**Issue by Rj426** [hideakitai/MAX17048#5]
Hi, I am trying to use Max17048 with esp32 board with the example provided here. 

i2c pins used -26,27

I am always getting 3.31 v on the serial monitor, although voltmeter is showing 4.1v.
![1D4BB427-1DBB-4A9E-ACB3-6C99A5CB86D0](https://user-images.githubusercontent.com/86737128/124001436-36908800-da07-11eb-8eac-a34f5b786b5c.jpeg)

can you help me to provide some pointers, if I am messing some configs.

Thanks

**Comment by hideakitai** [comment]
First, please check if `version()` method returns `0x1x`. `x` is depending the chip.

**Comment by Rj426** [comment]
here it is 
12:57:58.243 -> Device ID: 0x0C
12:57:58.243 -> Device version: 0x12

**Comment by hideakitai** [comment]
Hmm, I2C works correctly. I think it's the problem of hardware connection but it's not clear. Are you connecting battery to the VDD pin? The result indicates that VDD is connected to 3.3V....

**Comment by Rj426** [comment]
this is the board connection.
![image](https://user-images.githubusercontent.com/86737128/124063686-075d3380-da66-11eb-8795-073aebcdb26e.png)

VDD should be connected to +ve of battery or 3.3V.

**Comment by hideakitai** [comment]
MAX17048's VDD must be connected to battery. CELL pin is not internally connected. Power supply to VDD is 3.3V. So your result is correct.

![Screen Shot 2021-07-01 at 13 19 28](https://user-images.githubusercontent.com/889950/124064147-3330e700-da6f-11eb-9ee3-7bbaec3fbab1.png)

**Comment by Rj426** [comment]
oh ok. so looks like my conenction to VDD is wrong for current scematics. VDD should be directly connected to battery in my case then.
Thanks for your help.

**Comment by hideakitai** [comment]
Yes, that's right. Good luck!
