### ISSUE TITLE
Wrong voltage reading

### ISSUE THREAD

**Issue by Johnymalina** [hideakitai/MAX17048#6]
Hi,
iam using your library in following circuit: 
![max17048](https://github.com/hideakitai/MAX17048/assets/74618353/dd4a9742-cf10-4993-9901-8d9e1c8c1753)

and getting wrong voltage reading. Is there something i missed out? Actual voltmeter value is around 3,3V. 

```
VCELL ADC : 37008
VCELL V   : 2.89
VCELL SOC : 0 %
VCELL SOC : 0.00 %
```
No matter what battery i connect its always aprox. 0,5V off.

**Comment by hideakitai** [comment]
Sorry, I don't know why. But are you connecting the battery directly to the ESP32...? You may require a regulator between the battery and the esp32. Are you measuring the regulator's output (maybe 3.3V), and the actual battery output is about 2.9V?

**Comment by Johnymalina** [comment]
Sorry i forgot to close the issue. I resoldered the ic and now its all ok. Probably just a bad connection.
